#!/bin/sh

function HelpMessage() {
	echo "usage:
  calendar [-h] [-u] [-c]
options:
  -h Show this help message
  -u Update the ical file
  -c Run your calendar command in '$SCHOOL_DIR/.calendar"
	exit 0
}

function UpdateCalendar() {
	AssertCalendarExists
	curl -s $(cat "$SCHOOL_DIR"/".calendar_link") > "$SCHOOL_DIR"/".calendar.ics"
}

function RunCalendar() {
	AssertCalendarExists
	$("$SCHOOL_DIR"/".calendar") &
	exit 0
}

function AssertCalendarExists() {
	if [ ! -e "$SCHOOL_DIR"/".calendar_link" ] ; then
		echo ".calendar_link was not found in $SCHOOL_DIR"
		exit 1
	fi
}

if [ $# -eq 0 ] ; then
	HelpMessage
fi

while getopts huc OPT ; do
	case "$OPT" in
		h) HelpMessage;;
		u) UpdateCalendar;;
		c) RunCalendar;;
		*) HelpMessage;;
	esac
done

