#!/bin/sh

function HelpMessage () {
	# TODO: move to separate file?
	echo "usage: 
  brightwiz [-h|-l|-c|-a|-g] <class>
options:
  -h  Show this help message
  -l  List all classes
  -c  Open the Contents page for a class
  -a  Open the Assignments page for a class
  -g  Open the Grades page for a class"
	exit 1
}

function ListClasses () {
	echo list classes
	exit 1
}

function Contents () {
	echo contents page
	exit 1
}

function Assignments () {
	echo Assignments
	exit 1
}

function Grades () {
	echo Grades
	exit 1
}


if [ $# -lt 1 ] || [ $# -gt 2 ] ; then
	HelpMessage
fi

while getopts hlc:a:g OPT ; do 
	case "$OPT" in
		h) HelpMessage;;
		l) ListClasses;;
		c) Contents "$OPTARG";;
		a) Assignments "$OPTARG";;
		g) Grades "$OPTARG";;
		*) HelpMessage;;
	esac
done
